import {
  type InvariantViolation,
  assertConnectorResourceShapes,
  connectorResourceShapeViolations,
  entityStoreFor,
  installFetchMock,
  runPropertySyncTest,
} from '@rawdash/connector-test-utils';
import { InMemoryStorage } from '@rawdash/core';
import { afterEach, describe, it, vi } from 'vitest';
import { z } from 'zod';

import { StatuspageConnector } from './statuspage';

const docShapeExtra = (
  storage: InMemoryStorage,
  connectorId: string,
): InvariantViolation[] =>
  connectorResourceShapeViolations(
    StatuspageConnector.resources,
    storage,
    connectorId,
  );

const CONNECTOR_ID = 'statuspage';

type ComponentsSample = z.infer<typeof StatuspageConnector.schemas.components>;
type IncidentsSample = z.infer<typeof StatuspageConnector.schemas.incidents>;

describe('StatuspageConnector property tests', () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it('components: sync upholds universal invariants for any valid API payload', async () => {
    const extra = (
      storage: InMemoryStorage,
      _connectorId: string,
      sample: ComponentsSample,
    ): InvariantViolation[] => {
      const violations: InvariantViolation[] = [];
      const unique = new Set(sample.map((c) => c.id)).size;
      const written =
        entityStoreFor(storage, CONNECTOR_ID).get('statuspage_component')
          ?.size ?? 0;
      if (written !== unique) {
        violations.push({
          invariant: 'one statuspage_component entity per unique component id',
          location: 'components phase',
          detail: `expected ${unique} entities, got ${written}`,
        });
      }
      return violations;
    };

    await runPropertySyncTest({
      connectorClass: StatuspageConnector,
      resource: 'components',
      connectorId: CONNECTOR_ID,
      runs: 50,
      extraInvariants: [extra, docShapeExtra],
      run: async (sample, storage) => {
        // Returning a short page (length < PAGE_SIZE=100) terminates pagination.
        installFetchMock(() => sample);
        const connector = new StatuspageConnector(
          { pageId: 'page-1', resources: ['components'] },
          { apiKey: 'api-test' as unknown as { $secret: string } },
        );
        await connector.sync(
          { mode: 'full' },
          storage.getStorageHandle(CONNECTOR_ID),
        );
      },
    });
  });

  it('incidents: sync upholds universal invariants for any valid API payload', async () => {
    await runPropertySyncTest({
      connectorClass: StatuspageConnector,
      resource: 'incidents',
      connectorId: CONNECTOR_ID,
      runs: 50,
      extraInvariants: [docShapeExtra],
      run: async (sample: IncidentsSample, storage) => {
        installFetchMock(() => sample);
        // Use a since far in the past so the lookback window never drops
        // arbitrary-dated incidents generated by fast-check.
        const connector = new StatuspageConnector(
          {
            pageId: 'page-1',
            resources: ['incidents', 'incident_updates'],
          },
          { apiKey: 'api-test' as unknown as { $secret: string } },
        );
        await connector.sync(
          { mode: 'latest', since: '1970-01-01T00:00:00.000Z' },
          storage.getStorageHandle(CONNECTOR_ID),
        );
      },
    });
  });

  it('full sync across all resources matches documented shapes', async () => {
    installFetchMock((url) => {
      if (url.includes('/components')) {
        return [
          {
            id: 'c1',
            page_id: 'page-1',
            name: 'API',
            status: 'operational',
            group_id: null,
          },
        ];
      }
      if (url.includes('/incidents')) {
        return [
          {
            id: 'inc1',
            name: 'Outage',
            status: 'resolved',
            impact: 'minor',
            page_id: 'page-1',
            created_at: new Date(Date.now() - 60_000).toISOString(),
            updated_at: new Date(Date.now() - 60_000).toISOString(),
            resolved_at: new Date(Date.now() - 60_000).toISOString(),
            incident_updates: [
              {
                id: 'u1',
                incident_id: 'inc1',
                status: 'resolved',
                body: 'fixed',
                display_at: new Date(Date.now() - 60_000).toISOString(),
                created_at: new Date(Date.now() - 60_000).toISOString(),
              },
            ],
          },
        ];
      }
      return [];
    });

    const storage = new InMemoryStorage();
    const connector = new StatuspageConnector(
      {
        pageId: 'page-1',
        resources: ['components', 'incidents', 'incident_updates'],
      },
      { apiKey: 'api-test' as unknown as { $secret: string } },
    );
    await connector.sync(
      { mode: 'full' },
      storage.getStorageHandle(CONNECTOR_ID),
    );

    assertConnectorResourceShapes(
      StatuspageConnector.resources,
      storage,
      CONNECTOR_ID,
    );
  });
});
