// AUTO-GENERATED by scripts/bundle-migrations.ts — do not edit by hand.
// Regenerate with: pnpm db:bundle (or pnpm db:generate).

export interface BundledMigration {
  tag: string;
  statements: string[];
}

export const MIGRATIONS: readonly BundledMigration[] = [
  {
    tag: '0000_nosy_wendell_vaughn',
    statements: [
      "CREATE TABLE `distributions` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`connector_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`ts` integer NOT NULL,\n\t`kind` text NOT NULL,\n\t`data` text NOT NULL,\n\t`attributes` text DEFAULT '{}' NOT NULL\n);",
      'CREATE INDEX `distributions_conn_name_ts` ON `distributions` (`connector_id`,`name`,`ts`);',
      "CREATE TABLE `edges` (\n\t`connector_id` text NOT NULL,\n\t`from_type` text NOT NULL,\n\t`from_id` text NOT NULL,\n\t`kind` text NOT NULL,\n\t`to_type` text NOT NULL,\n\t`to_id` text NOT NULL,\n\t`attributes` text DEFAULT '{}' NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tPRIMARY KEY(`connector_id`, `from_type`, `from_id`, `kind`, `to_type`, `to_id`)\n);",
      'CREATE INDEX `edges_conn_kind` ON `edges` (`connector_id`,`kind`);',
      'CREATE INDEX `edges_conn_from` ON `edges` (`connector_id`,`from_type`,`from_id`);',
      "CREATE TABLE `entities` (\n\t`connector_id` text NOT NULL,\n\t`type` text NOT NULL,\n\t`id` text NOT NULL,\n\t`attributes` text DEFAULT '{}' NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tPRIMARY KEY(`connector_id`, `type`, `id`)\n);",
      'CREATE INDEX `entities_conn_type` ON `entities` (`connector_id`,`type`);',
      "CREATE TABLE `events` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`connector_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`start_ts` integer NOT NULL,\n\t`end_ts` integer,\n\t`attributes` text DEFAULT '{}' NOT NULL\n);",
      'CREATE INDEX `events_conn_name_start` ON `events` (`connector_id`,`name`,`start_ts`);',
      "CREATE TABLE `metrics` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`connector_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`ts` integer NOT NULL,\n\t`value` real NOT NULL,\n\t`attributes` text DEFAULT '{}' NOT NULL\n);",
      'CREATE INDEX `metrics_conn_name_ts` ON `metrics` (`connector_id`,`name`,`ts`);',
    ],
  },
  {
    tag: '0001_clumsy_siren',
    statements: [
      'CREATE TABLE `sync_state` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`status` text NOT NULL,\n\t`last_sync_at` text,\n\t`last_error` text\n);',
    ],
  },
  {
    tag: '0002_milky_echo',
    statements: [
      'ALTER TABLE `sync_state` ADD `queued_at` text;',
      'ALTER TABLE `sync_state` ADD `started_at` text;',
    ],
  },
] as const;
