export type {
  CachedWidget,
  ConfiguredConnector,
  ConnectorHealth,
  DashboardConfig,
  HealthResponse,
  ServerStorage,
  SyncState,
  SyncStatus,
  TriggerSyncResponse,
  Widget,
  WidgetStatus,
  WidgetSyncState,
  WidgetsListResponse,
} from '@rawdash/core';
